[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Agent", "Model", "Provider", "Vendor/mistral", "Area/AI", "Type/Connector"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.mistral"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.mistral"
version = "1.2.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.mistral-native"
version = "1.2.1"
path = "../native/build/libs/ai.mistral-native-1.2.1.jar"
