[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Mistral", "Model", "Provider"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.mistral"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.mistral"
version = "1.2.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.mistral-native"
version = "1.2.0"
path = "../native/build/libs/ai.mistral-native-1.2.0-SNAPSHOT.jar"
