[plugin]
id = "ai-mistral-compiler-plugin"
class = "io.ballerina.lib.ai.mistral.AiMistralCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.mistral-compiler-plugin-1.2.0.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"
